### ISSUE TITLE
not working : Error(kindlegen):E30005

### ISSUE THREAD

**Issue by dhruv-bansal** [ViciousPotato/safaribooks#12]
getting error:

Error(kindlegen):E30005: Could not find file  *.epub

**Comment by ViciousPotato** [comment]
Hi could you paste the whole log here (without your user name and pass), it seems something went wrong downloading the book.

Thanks

**Comment by blacpythoz** [comment]
I had install in local user and got this error:
`
Traceback (most recent call last):
  File "/home/deadsec/.local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/deadsec/.local/lib/python3.6/site-packages/scrapy/cmdline.py", line 148, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/home/deadsec/.local/lib/python3.6/site-packages/scrapy/crawler.py", line 243, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/home/deadsec/.local/lib/python3.6/site-packages/scrapy/crawler.py", line 134, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/home/deadsec/.local/lib/python3.6/site-packages/scrapy/crawler.py", line 330, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/home/deadsec/.local/lib/python3.6/site-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/home/deadsec/.local/lib/python3.6/site-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/home/deadsec/.local/lib/python3.6/site-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/home/deadsec/.local/lib/python3.6/site-packages/scrapy/utils/misc.py", line 63, in walk_modules
    mod = import_module(path)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/deadsec/temp/safaribooks/safaribook/spiders/__init__.py", line 6, in <module>
    from safaribooks import SafariBooksSpider
ModuleNotFoundError: No module named 'safaribooks'

*************************************************************
 Amazon kindlegen(Linux) V2.9 build 1028-0897292 
 A command line e-book compiler 
 Copyright Amazon.com and its Affiliates 2014 
*************************************************************

Error(kindlegen):E30005: Could not find file  *.epub
`
