### ISSUE TITLE
Redirecting (302) when downloading images for book

### ISSUE THREAD

**Issue by Knrj** [ViciousPotato/safaribooks#17]
**Bookid** = 9781935504634

**DEBUG ERRORS**
2017-12-07 21:31:54 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET https://www.safaribooksonline.com/static/images/default_cover.9943b5969cc4.png> from <GET https://www.safaribooksonline.com//library/view/enterprise-architecture-made/9781935504634/images/EnterpriseArchitecture_fmt5.png>
2017-12-07 21:31:54 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET https://www.safaribooksonline.com/static/images/default_cover.9943b5969cc4.png> from <GET https://www.safaribooksonline.com//library/view/enterprise-architecture-made/9781935504634/images/EnterpriseArchitectur_fmt51.png>

**Comment by ViciousPotato** [comment]
@Knrj Hi this issue is fixed, please try and let me know.

Thanks

**Comment by Knrj** [comment]
thanks! i tried downloading your new spider file but now get this

---------------
Traceback (most recent call last):
  File "/home/kristofferj/.local/bin/scrapy", line 11, in <module>
    sys.exit(execute())
  File "/home/kristofferj/.local/lib/python2.7/site-packages/scrapy/cmdline.py", line 148, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "/home/kristofferj/.local/lib/python2.7/site-packages/scrapy/crawler.py", line 243, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/home/kristofferj/.local/lib/python2.7/site-packages/scrapy/crawler.py", line 134, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/home/kristofferj/.local/lib/python2.7/site-packages/scrapy/crawler.py", line 330, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/home/kristofferj/.local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/home/kristofferj/.local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/home/kristofferj/.local/lib/python2.7/site-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/home/kristofferj/.local/lib/python2.7/site-packages/scrapy/utils/misc.py", line 63, in walk_modules
    mod = import_module(path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/kristofferj/safaribooks/safaribook/spiders/__init__.py", line 6, in <module>
    from safaribooks import SafariBooksSpider
  File "/home/kristofferj/safaribooks/safaribook/spiders/safaribooks.py", line 7
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax


---------------

**Comment by Knrj** [comment]
Duh!!!!! my mistake! did a wget without auth!!!!
