### ISSUE TITLE
Python version can't find spider and docker version doesn't copy file to local machine

### ISSUE THREAD

**Issue by dennissheppard** [ViciousPotato/safaribooks#26]
Running the `safaribooks` script gives me this error and trace: ```2018-01-29 20:56:11 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: scrapybot)
2018-01-29 20:56:11 [scrapy.utils.log] INFO: Versions: lxml 4.1.1.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.3.1, w3lib 1.19.0, Twisted 16.4.1, Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)], pyOpenSSL 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017), cryptography 2.1.4, Platform Windows-10-10.0.16299
Traceback (most recent call last):
  File "C:\Users\username\.windows-build-tools\python27\Scripts\safaribooks-script.py", line 11, in <module>
    load_entry_point('safaribooks==0.1.0', 'console_scripts', 'safaribooks')()
  File "c:\users\username\.windows-build-tools\python27\lib\site-packages\safaribooks\__main__.py", line 113, in main
    args.func(args)
  File "c:\users\username\.windows-build-tools\python27\lib\site-packages\safaribooks\__main__.py", line 24, in download_epub
    output_directory=args.output_directory,
  File "c:\users\username\.windows-build-tools\python27\lib\site-packages\scrapy\crawler.py", line 170, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "c:\users\username\.windows-build-tools\python27\lib\site-packages\scrapy\crawler.py", line 198, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "c:\users\username\.windows-build-tools\python27\lib\site-packages\scrapy\crawler.py", line 202, in _create_crawler
    spidercls = self.spider_loader.load(spidercls)
  File "c:\users\username\.windows-build-tools\python27\lib\site-packages\scrapy\spiderloader.py", line 71, in load
    raise KeyError("Spider not found: {}".format(spider_name))
KeyError: 'Spider not found: SafariBooks'```

And it looks like the docker version does generate the files, but doesn't copy to the "converted" folder. Not sure how to actually get the files off the docker vm.

**Comment by dennissheppard** [comment]
I'm assuming you're referring to the docker not copying files to the converted folder? Converted is created. And the files are created on the docker vm, just never moved.

>  Made archive /app/book-i-want.zip
> 2018-01-29 22:18:06 [SafariBooks] INFO: Moving /app/book-i-want.zip to /app/converted/book-i-want-97543432234.epub

**Comment by dennissheppard** [comment]
Was able to get the manual/python version to work, so edited the first item. Docker version still has the no copying issue. I don't need the docker version if the first works, so not a problem for me. But someone else may come along needing assistance.
