### ISSUE TITLE
What´s the correct sintax for SSO downloads?

### ISSUE THREAD

**Issue by Gamartto** [ViciousPotato/safaribooks#31]
Hi, 

I´m trying to use my SSO account to download some ebooks using this command line 

`safaribooks -o "C:\Users\Admin\Desktop\books" -u **myUsername** -p **myPassword** -b 9781617294167 -c 'BrowserCookie=AAAAA-BBBBB-CCCCC-DDDDD-EEEEEEEE; sessionid=AAABBBCCCDDDEEE' download-epub`

But I´m receiving this error

2018-01-31 14:18:20 [scrapy.utils.log] INFO: Scrapy 1.5.0 started (bot: scrapybot)
2018-01-31 14:18:20 [scrapy.utils.log] INFO: Versions: lxml 4.1.1.0, libxml2 2.9.5, cssselect 1.0.3, parsel 1.3.1, w3lib 1.19.0, Twisted 16.4.1, Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)], pyOpenSSL 17.5.0 (OpenSSL 1.1.0g  2 Nov 2017), cryptography 2.1.4, Platform Windows-10-10.0.16299
Traceback (most recent call last):
  File "C:\Python27\Scripts\safaribooks-script.py", line 11, in <module>
    load_entry_point('safaribooks==0.1.0', 'console_scripts', 'safaribooks')()
  File "c:\python27\lib\site-packages\safaribooks\__main__.py", line 121, in main
    args.func(args)
  File "c:\python27\lib\site-packages\safaribooks\__main__.py", line 28, in download_epub
    output_directory=args.output_directory
  File "c:\python27\lib\site-packages\scrapy\crawler.py", line 170, in crawl
    crawler = self.create_crawler(crawler_or_spidercls)
  File "c:\python27\lib\site-packages\scrapy\crawler.py", line 198, in create_crawler
    return self._create_crawler(crawler_or_spidercls)
  File "c:\python27\lib\site-packages\scrapy\crawler.py", line 202, in _create_crawler
    spidercls = self.spider_loader.load(spidercls)
  File "c:\python27\lib\site-packages\scrapy\spiderloader.py", line 71, in load
    raise KeyError("Spider not found: {}".format(spider_name))
KeyError: 'Spider not found: SafariBooks'

What could be the issue here? The program was installed correctly AFAIK.

Thanks.

**Comment by sanmibuh** [comment]
Which password do you use @Gamartto ?
I have only my email username, because after put my email on the safaribooks web, it goes to my company's SSO for login.

**Comment by sanmibuh** [comment]
Done!!
You dont need to pass user nor password. Pass the cookie itself (you can get it after login it on any browser )

`-c COOKIE, --cookie COOKIE 
                        Safari Books Online Cookie. This filed can be retrieved by
                        using Chrome and copying request as curl. Cookie input should
                        be included in ''.
                        Example:
                        'BrowserCookie=XXXXXXXXXXXXXXXXXXXXX; sessionid=XXXXXXXXXXXXXXXXX;'`

**Comment by Gamartto** [comment]
Didnt work for me... Downloaded ebooks are 9K in size.
