### ISSUE TITLE
TabError when running via Docker

### ISSUE THREAD

**Issue by rencire** [ViciousPotato/safaribooks#33]
hi, I tried running the docker command on README and get this stacktrace:

```
Traceback (most recent call last):
  File "/usr/local/bin/safaribooks", line 11, in <module>
    load_entry_point('safaribooks', 'console_scripts', 'safaribooks')()
  File "/app/safaribooks/__main__.py", line 121, in main
    args.func(args)
  File "/app/safaribooks/__main__.py", line 55, in download
    download_epub(args)
  File "/app/safaribooks/__main__.py", line 21, in download_epub
    process = CrawlerProcess(get_project_settings())
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 249, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 137, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "/usr/local/lib/python3.6/site-packages/scrapy/crawler.py", line 336, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "/usr/local/lib/python3.6/site-packages/scrapy/spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "/usr/local/lib/python3.6/site-packages/scrapy/spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "/usr/local/lib/python3.6/site-packages/scrapy/spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "/usr/local/lib/python3.6/site-packages/scrapy/utils/misc.py", line 63, in walk_modules
    mod = import_module(path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/safaribooks/spiders/__init__.py", line 6, in <module>
    from .safaribooks import SafariBooksSpider  # noqa
  File "/app/safaribooks/spiders/safaribooks.py", line 134
    style_sheets = page_json.get('stylesheets', [])
                                                  ^
TabError: inconsistent use of tabs and spaces in indentation
```

Any ideas why this is happening?

**Comment by BM27** [comment]
I was able to resolve this one with a few spacing edits. (python is quite particular with spacing)

First delete the existing docker image that was built.

docker images
docker rmi IMAGEID

Then I edited this file in notepad:   spiders/safaribooks.py

Lines 134 and 135 use a tab instead of spaces. Replace the tab with 4 spaces. Then add 4 more spaces for a total of 8 spaces from the start of the line. (This is so that it is aligned with the function parse_page_json)

I'm not versed in Git so I hesitate to update this file myself. However, I suspect the author can attend to this himself shortly.

rebuild the image and everything is working as expected!

```
        style_sheets = page_json.get('stylesheets', [])
        style_sheets_paths = []
```
