### ISSUE TITLE
Error: 'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by EdoBarroso** [ViciousPotato/safaribooks#45]
I just ran this through Docker and got this error message all across the log:

```2018-05-22 20:57:27 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.safaribooksonline.com/api/v1/book/9780133478549/chapter-content/copyright.html> (referer: https://www.safaribooksonline.com//api/v1/book/9780133478549/chapter/copyright.html)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/scrapy/utils/defer.py", line 102, in iter_errback
    yield next(it)
  File "/usr/local/lib/python3.6/site-packages/scrapy/spidermiddlewares/offsite.py", line 30, in process_spider_output
    for x in result:
  File "/usr/local/lib/python3.6/site-packages/scrapy/spidermiddlewares/referer.py", line 339, in <genexpr>
    return (_set_referer(r) for r in result or ())
  File "/usr/local/lib/python3.6/site-packages/scrapy/spidermiddlewares/urllength.py", line 37, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/usr/local/lib/python3.6/site-packages/scrapy/spidermiddlewares/depth.py", line 58, in <genexpr>
    return (r for r in result or () if _filter(r))
  File "/app/safaribooks/spiders/safaribooks.py", line 177, in parse_page
    body = str(BeautifulSoup(response.body, 'lxml').find('body')).decode('utf8')
AttributeError: 'str' object has no attribute 'decode'

**Comment by EdoBarroso** [comment]
There's a generated EPUB, but it's unreadable

**Comment by ViciousPotato** [comment]
Hey @EdoBarroso it is caused by py3 incompatibility and fixed now.

Please try again and let me know if works.
