### ISSUE TITLE
After Downloading Book is in Epub Format it given an Error , I gave parameter Download 

### ISSUE THREAD

**Issue by Abhi904485** [ViciousPotato/safaribooks#47]
018-06-17 02:19:37 [SafariBooks] INFO: Moving C:\Users\Abhishek\Downloads\Compressed\safaribooks-master\safaribooks\pandas-for-everyone.zip to C:\Users\Abhishek\Downloads\Compressed\safaribooks-master\safaribooks\converted\Pandas_for_Everyone__Python_Data_Analysis,_First_Edition-9780134547046.epub
2018-06-17 02:19:37 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 132017,
 'downloader/request_count': 202,
 'downloader/request_method_count/GET': 201,
 'downloader/request_method_count/POST': 1,
 'downloader/response_bytes': 7168303,
 'downloader/response_count': 202,
 'downloader/response_status_count/200': 201,
 'downloader/response_status_count/302': 1,
 'dupefilter/filtered': 55,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 6, 16, 20, 49, 35, 794000),
 'log_count/DEBUG': 1745,
 'log_count/INFO': 12,
 'request_depth_max': 5,
 'response_received_count': 201,
 'scheduler/dequeued': 202,
 'scheduler/dequeued/memory': 202,
 'scheduler/enqueued': 202,
 'scheduler/enqueued/memory': 202,
 'start_time': datetime.datetime(2018, 6, 16, 20, 47, 32, 366000)}
2018-06-17 02:19:37 [scrapy.core.engine] INFO: Spider closed (finished)
C:\Users\Abhishek\Downloads\Compressed\safaribooks-master\safaribooks\converted
Traceback (most recent call last):
  File "C:\Python27\Scripts\safaribooks-script.py", line 11, in <module>
    load_entry_point('safaribooks==0.1.1', 'console_scripts', 'safaribooks')()
  File "c:\python27\lib\site-packages\safaribooks\__main__.py", line 121, in main
    args.func(args)
  File "c:\python27\lib\site-packages\safaribooks\__main__.py", line 60, in download
    convert_to_mobi(args)
  File "c:\python27\lib\site-packages\safaribooks\__main__.py", line 51, in convert_to_mobi
    subprocess.call(['kindlegen', path])
  File "c:\python27\lib\subprocess.py", line 168, in call
    return Popen(*popenargs, **kwargs).wait()
  File "c:\python27\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "c:\python27\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] The system cannot find the file specified

**Comment by mjteebone** [comment]
it seems like you are missing kindlegen (requirement defined in readme)
