### ISSUE TITLE
No form element found in 200 https://www.oreilly.com

### ISSUE THREAD

**Issue by andrewvn2010** [ViciousPotato/safaribooks#56]
2018-11-29 14:46:52 [scrapy.core.engine] INFO: Spider opened
2018-11-29 14:46:52 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-11-29 14:46:52 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2018-11-29 14:46:53 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (301) to <GET https://www.oreilly.com> from <GET https://www.safaribooksonline.com/>
2018-11-29 14:46:54 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.oreilly.com> (referer: None)
2018-11-29 14:46:54 **[scrapy.core.scraper] ERROR: Spider error processing <GET https://www.oreilly.com> (referer: None)**
Traceback (most recent call last):
 

>  File "/usr/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
>     current.result = callback(current.result, *args, **kw)
>   File "/usr/local/lib/python2.7/site-packages/safaribooks/spiders/safaribooks.py", line 103, in parse
>     callback=self.after_login
>   File "/usr/local/lib/python2.7/site-packages/scrapy/http/request/form.py", line 48, in from_response
>     form = _get_form(response, formname, formid, formnumber, formxpath)
>   File "/usr/local/lib/python2.7/site-packages/scrapy/http/request/form.py", line 77, in _get_form
>     raise ValueError("No <form> element found in %s" % response)

**ValueError: No <form> element found in <200 https://www.oreilly.com>**
2018-11-29 14:46:55 [scrapy.core.engine] INFO: Closing spider (finished)
2018-11-29 14:46:55 [SafariBooks] INFO: Did not even got toc, ignore generated file operation.
2018-11-29 14:46:55 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 438,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 8519,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/301': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 11, 29, 7, 46, 55, 95761),
 'log_count/DEBUG': 3,
 'log_count/ERROR': 1,
 'log_count/INFO': 9,
 'memusage/max': 48963584,
 'memusage/startup': 48963584,
 'response_received_count': 1,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'spider_exceptions/ValueError': 1,
 'start_time': datetime.datetime(2018, 11, 29, 7, 46, 52, 397288)}
2018-11-29 14:46:55 [scrapy.core.engine] INFO: Spider closed (finished)

**Comment by owen800q** [comment]
2018-12-01 08:16:11 [scrapy.utils.log] INFO: Scrapy 1.5.1 started (bot: safaribooks)
2018-12-01 08:16:11 [scrapy.utils.log] INFO: Versions: lxml 4.2.5.0, libxml2 2.9.8, cssselect 1.0.3, parsel 1.5.1, w3lib 1.19.0, Twisted 16.4.1, Python 3.6.7 (default, Nov 16 2018, 06:56:26) - [GCC 6.4.0], pyOpenSSL 18.0.0 (OpenSSL 1.0.2q  20 Nov 2018), cryptography 2.4.2, Platform Linux-4.15.0-39-generic-x86_64-with
2018-12-01 08:16:11 [scrapy.crawler] INFO: Overridden settings: {'BOT_NAME': 'safaribooks', 'DOWNLOAD_DELAY': 0.25, 'NEWSPIDER_MODULE': 'safaribooks.spiders', 'SPIDER_MODULES': ['safaribooks.spiders']}
2018-12-01 08:16:11 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats']
2018-12-01 08:16:11 [SafariBooks] INFO: Using `/tmp/tmpawsy524_` as temporary directory
2018-12-01 08:16:11 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2018-12-01 08:16:11 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2018-12-01 08:16:11 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2018-12-01 08:16:11 [scrapy.core.engine] INFO: Spider opened
2018-12-01 08:16:11 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2018-12-01 08:16:11 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2018-12-01 08:16:12 [scrapy.downloadermiddlewares.redirect] DEBUG: Redirecting (302) to <GET https://www.oreilly.com> from <GET https://www.safaribooksonline.com>
2018-12-01 08:16:12 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.oreilly.com> (referer: None)
2018-12-01 08:16:12 [scrapy.core.scraper] ERROR: Spider error processing <GET https://www.oreilly.com> (referer: None)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/twisted/internet/defer.py", line 587, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/app/safaribooks/spiders/safaribooks.py", line 103, in parse
    callback=self.after_login
  File "/usr/local/lib/python3.6/site-packages/scrapy/http/request/form.py", line 48, in from_response
    form = _get_form(response, formname, formid, formnumber, formxpath)
  File "/usr/local/lib/python3.6/site-packages/scrapy/http/request/form.py", line 77, in _get_form
    raise ValueError("No <form> element found in %s" % response)
ValueError: No <form> element found in <200 https://www.oreilly.com>
2018-12-01 08:16:12 [scrapy.core.engine] INFO: Closing spider (finished)
2018-12-01 08:16:12 [SafariBooks] INFO: Did not even got toc, ignore generated file operation.
2018-12-01 08:16:12 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 438,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 8789,
 'downloader/response_count': 2,
 'downloader/response_status_count/200': 1,
 'downloader/response_status_count/302': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2018, 12, 1, 8, 16, 12, 900070),
 'log_count/DEBUG': 3,
 'log_count/ERROR': 1,
 'log_count/INFO': 9,
 'memusage/max': 55107584,
 'memusage/startup': 55107584,
 'response_received_count': 1,
 'scheduler/dequeued': 2,
 'scheduler/dequeued/memory': 2,
 'scheduler/enqueued': 2,
 'scheduler/enqueued/memory': 2,
 'spider_exceptions/ValueError': 1,
 'start_time': datetime.datetime(2018, 12, 1, 8, 16, 11, 408246)}
2018-12-01 08:16:12 [scrapy.core.engine] INFO: Spider closed (finished)
/app/converted
Traceback (most recent call last):
  File "/usr/local/bin/safaribooks", line 11, in <module>
    load_entry_point('safaribooks', 'console_scripts', 'safaribooks')()
  File "/app/safaribooks/__main__.py", line 121, in main
    args.func(args)
  File "/app/safaribooks/__main__.py", line 60, in download
    convert_to_mobi(args)
  File "/app/safaribooks/__main__.py", line 49, in convert_to_mobi
    )[0]
IndexError: list index out of range

**Comment by vitalysim** [comment]
The login page was moved to : https://www.safaribooksonline.com/accounts/login/

**Comment by vitalysim** [comment]
Fixed: 
https://github.com/ViciousPotato/safaribooks/pull/57

**Comment by andrewvn2010** [comment]
thanks
