### ISSUE TITLE
ERROR: Error downloading <GET https://www.safaribooksonline.com/>

### ISSUE THREAD

**Issue by fpoumian** [ViciousPotato/safaribooks#7]
I'm trying to download a book but I'm getting this error. Any ideas?

``` shell
2017-07-26 17:07:57 [scrapy.utils.log] INFO: Scrapy 1.4.0 started (bot: safaribook)
2017-07-26 17:07:57 [scrapy.utils.log] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'safaribook.spiders', 'SPIDER_MODULES': ['safaribook.spiders'], 'DOWNLOAD_DELAY': 0.25, 'BOT_NAME': 'safaribook'}
2017-07-26 17:07:57 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.memusage.MemoryUsage',
 'scrapy.extensions.logstats.LogStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.corestats.CoreStats']
2017-07-26 17:07:57 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2017-07-26 17:07:57 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2017-07-26 17:07:57 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2017-07-26 17:07:57 [scrapy.core.engine] INFO: Spider opened
2017-07-26 17:07:57 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2017-07-26 17:07:57 [scrapy.extensions.telnet] DEBUG: Telnet console listening on 127.0.0.1:6023
2017-07-26 17:07:57 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.safaribooksonline.com/>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 1384, in _inlineCallbacks
    result = result.throwExceptionIntoGenerator(g)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/failure.py", line 393, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/middleware.py", line 43, in process_request
    defer.returnValue((yield download_func(request=request,spider=spider)))
  File "/usr/local/lib/python2.7/dist-packages/scrapy/utils/defer.py", line 45, in mustbe_deferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/handlers/__init__.py", line 65, in download_request
    return handler.download_request(request, spider)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/handlers/http11.py", line 63, in download_request
    return agent.download_request(request)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/handlers/http11.py", line 300, in download_request
    method, to_bytes(url, encoding='ascii'), headers, bodyproducer)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1633, in request
    endpoint = self._getEndpoint(parsedURI)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1617, in _getEndpoint
    return self._endpointFactory.endpointForURI(uri)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/client.py", line 1494, in endpointForURI
    uri.port)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/contextfactory.py", line 59, in creatorForNetloc
    return ScrapyClientTLSOptions(hostname.decode("ascii"), self.getContext())
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/contextfactory.py", line 56, in getContext
    return self.getCertificateOptions().getContext()
  File "/usr/local/lib/python2.7/dist-packages/scrapy/core/downloader/contextfactory.py", line 51, in getCertificateOptions
    acceptableCiphers=DEFAULT_CIPHERS)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/deprecate.py", line 792, in wrapped
    return wrappee(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 1583, in __init__
    self._options |= SSL.OP_SINGLE_DH_USE | SSL.OP_SINGLE_ECDH_USE
AttributeError: 'module' object has no attribute 'OP_SINGLE_ECDH_USE'
2017-07-26 17:07:57 [scrapy.core.engine] INFO: Closing spider (finished)
2017-07-26 17:07:57 [scrapy.utils.signal] ERROR: Error caught on signal handler: <function close at 0x7fd5798c9938>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/defer.py", line 150, in maybeDeferred
    result = f(*args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pydispatch/robustapply.py", line 55, in robustApply
    return receiver(*arguments, **named)
  File "/usr/local/lib/python2.7/dist-packages/scrapy/spiders/__init__.py", line 104, in close
    return closed(reason)
  File "/home/fpoumian/Code/safaribooks/safaribook/spiders/safaribooks.py", line 106, in closed
    shutil.move(self.book_name + '.zip', self.book_name + '.epub')
  File "/usr/lib/python2.7/shutil.py", line 302, in move
    copy2(src, real_dst)
  File "/usr/lib/python2.7/shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '.zip'
2017-07-26 17:07:57 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/exceptions.AttributeError': 1,
 'downloader/request_bytes': 227,
 'downloader/request_count': 1,
 'downloader/request_method_count/GET': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2017, 7, 26, 23, 7, 57, 664761),
 'log_count/DEBUG': 1,
 'log_count/ERROR': 2,
 'log_count/INFO': 7,
 'memusage/max': 68534272,
 'memusage/startup': 68534272,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2017, 7, 26, 23, 7, 57, 352402)}
2017-07-26 17:07:57 [scrapy.core.engine] INFO: Spider closed (finished)

*************************************************************
 Amazon kindlegen(Linux) V2.9 build 1028-0897292 
 A command line e-book compiler 
 Copyright Amazon.com and its Affiliates 2014 
*************************************************************

Error(kindlegen):E30005: Could not find file  *.epub

```

**Comment by ViciousPotato** [comment]
Hi sorry, I did not see the message till now.

Could you pull again and run `pip install -r requirements.txt` to update package versions, if you are still interested?

If it fails could you run 

`sudo apt-get install libssl-dev`
`pip install pyopenssl --upgrade`

and let me know if it works?

Thanks
